export const FETCH_FOLDERS = "FETCH_FOLDERS";
export const ADD_FOLDER = "ADD_FOLDER";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const UPDATE_FOLDER = "UPDATE_FOLDER";

export const FETCH_LETTERS = "FETCH_LETTERS";

export const OPEN_EDIT_MODAL_FOLDER = "OPEN_EDIT_MODAL_FOLDER";
export const OPEN_CREATE_MODAL_FOLDER = "OPEN_CREATE_MODAL_FOLDER";
export const CLOSE_MODAL_FOLDER = "CLOSE_MODAL_EDIT_FOLDER";
